name: gift_card
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_svg: ^2.0.9
  hooks_riverpod: ^2.4.5
  intl: ^0.18.1
  riverpod_annotation: ^2.3.0
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/card/
    - assets/icon/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/merriweather/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Light.ttf
          weight: 300
        - asset: assets/fonts/merriweather/Merriweather-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/merriweather/Merriweather-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Black.ttf
          weight: 900
        - asset: assets/fonts/merriweather/Merriweather-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Playfair
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/playfair/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic

scripts: derry.yaml
